<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('location_countries')->truncate();

    	$countries = array(
    		array('id' => 1, 'name' => "Afghanistan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 2, 'name' => "Albania", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 3, 'name' => "Algeria", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 4, 'name' => "American Samoa", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 5, 'name' => "Andorra", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 6, 'name' => "Angola", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 7, 'name' => "Anguilla", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 8, 'name' => "Antarctica", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 9, 'name' => "Antigua And Barbuda", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 10, 'name' => "Argentina", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 11, 'name' => "Armenia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 12, 'name' => "Aruba", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 13, 'name' => "Australia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 14, 'name' => "Austria", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 15, 'name' => "Azerbaijan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 16, 'name' => "Bahamas The", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 17, 'name' => "Bahrain", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 18, 'name' => "Bangladesh", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 19, 'name' => "Barbados", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 20, 'name' => "Belarus", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 21, 'name' => "Belgium", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 22, 'name' => "Belize", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 23, 'name' => "Benin", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 24, 'name' => "Bermuda", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 25, 'name' => "Bhutan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 26, 'name' => "Bolivia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 27, 'name' => "Bosnia and Herzegovina", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 28, 'name' => "Botswana", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 29, 'name' => "Bouvet Island", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 30, 'name' => "Brazil", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 31, 'name' => "British Indian Ocean Territory", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 32, 'name' => "Brunei", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 33, 'name' => "Bulgaria", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 34, 'name' => "Burkina Faso", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 35, 'name' => "Burundi", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 36, 'name' => "Cambodia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 37, 'name' => "Cameroon", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 38, 'name' => "Canada", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 39, 'name' => "Cape Verde", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 40, 'name' => "Cayman Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 41, 'name' => "Central African Republic", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 42, 'name' => "Chad", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 43, 'name' => "Chile", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 44, 'name' => "China", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 45, 'name' => "Christmas Island", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 46, 'name' => "Cocos (Keeling) Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 47, 'name' => "Colombia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 48, 'name' => "Comoros", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 49, 'name' => "Congo", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 50, 'name' => "Congo The Democratic Republic Of The", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 51, 'name' => "Cook Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 52, 'name' => "Costa Rica", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 53, 'name' => "Cote D Ivoire (Ivory Coast)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 54, 'name' => "Croatia (Hrvatska)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 55, 'name' => "Cuba", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 56, 'name' => "Cyprus", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 57, 'name' => "Czech Republic", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 58, 'name' => "Denmark", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 59, 'name' => "Djibouti", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 60, 'name' => "Dominica", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 61, 'name' => "Dominican Republic", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 62, 'name' => "East Timor", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 63, 'name' => "Ecuador", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 64, 'name' => "Egypt", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 65, 'name' => "El Salvador", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 66, 'name' => "Equatorial Guinea", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 67, 'name' => "Eritrea", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 68, 'name' => "Estonia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 69, 'name' => "Ethiopia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 70, 'name' => "External Territories of Australia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 71, 'name' => "Falkland Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 72, 'name' => "Faroe Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 73, 'name' => "Fiji Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 74, 'name' => "Finland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 75, 'name' => "France", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 76, 'name' => "French Guiana", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 77, 'name' => "French Polynesia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 78, 'name' => "French Southern Territories", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 79, 'name' => "Gabon", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 80, 'name' => "Gambia The", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 81, 'name' => "Georgia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 82, 'name' => "Germany", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 83, 'name' => "Ghana", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 84, 'name' => "Gibraltar", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 85, 'name' => "Greece", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 86, 'name' => "Greenland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 87, 'name' => "Grenada", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 88, 'name' => "Guadeloupe", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 89, 'name' => "Guam", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 90, 'name' => "Guatemala", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 91, 'name' => "Guernsey and Alderney", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 92, 'name' => "Guinea", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 93, 'name' => "Guinea-Bissau", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 94, 'name' => "Guyana", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 95, 'name' => "Haiti", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 96, 'name' => "Heard and McDonald Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 97, 'name' => "Honduras", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 98, 'name' => "Hong Kong S.A.R.", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 99, 'name' => "Hungary", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 100, 'name' => "Iceland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 101, 'name' => "India", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 102, 'name' => "Indonesia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 103, 'name' => "Iran", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 104, 'name' => "Iraq", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 105, 'name' => "Ireland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 106, 'name' => "Israel", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 107, 'name' => "Italy", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 108, 'name' => "Jamaica", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 109, 'name' => "Japan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 110, 'name' => "Jersey", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 111, 'name' => "Jordan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 112, 'name' => "Kazakhstan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 113, 'name' => "Kenya", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 114, 'name' => "Kiribati", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 115, 'name' => "Korea North", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 116, 'name' => "Korea South", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 117, 'name' => "Kuwait", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 118, 'name' => "Kyrgyzstan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 119, 'name' => "Laos", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 120, 'name' => "Latvia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 121, 'name' => "Lebanon", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 122, 'name' => "Lesotho", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 123, 'name' => "Liberia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 124, 'name' => "Libya", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 125, 'name' => "Liechtenstein", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 126, 'name' => "Lithuania", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 127, 'name' => "Luxembourg", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 128, 'name' => "Macau S.A.R.", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 129, 'name' => "Macedonia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 130, 'name' => "Madagascar", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 131, 'name' => "Malawi", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 132, 'name' => "Malaysia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 133, 'name' => "Maldives", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 134, 'name' => "Mali", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 135, 'name' => "Malta", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 136, 'name' => "Man (Isle of)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 137, 'name' => "Marshall Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 138, 'name' => "Martinique", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 139, 'name' => "Mauritania", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 140, 'name' => "Mauritius", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 141, 'name' => "Mayotte", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 142, 'name' => "Mexico", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 143, 'name' => "Micronesia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 144, 'name' => "Moldova", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 145, 'name' => "Monaco", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 146, 'name' => "Mongolia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 147, 'name' => "Montserrat", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 148, 'name' => "Morocco", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 149, 'name' => "Mozambique", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 150, 'name' => "Myanmar", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 151, 'name' => "Namibia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 152, 'name' => "Nauru", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 153, 'name' => "Nepal", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 154, 'name' => "Netherlands Antilles", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 155, 'name' => "Netherlands The", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 156, 'name' => "New Caledonia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 157, 'name' => "New Zealand", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 158, 'name' => "Nicaragua", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 159, 'name' => "Niger", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 160, 'name' => "Nigeria", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 161, 'name' => "Niue", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 162, 'name' => "Norfolk Island", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 163, 'name' => "Northern Mariana Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 164, 'name' => "Norway", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 165, 'name' => "Oman", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 166, 'name' => "Pakistan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 167, 'name' => "Palau", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 168, 'name' => "Palestinian Territory Occupied", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 169, 'name' => "Panama", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 170, 'name' => "Papua new Guinea", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 171, 'name' => "Paraguay", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 172, 'name' => "Peru", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 173, 'name' => "Philippines", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 174, 'name' => "Pitcairn Island", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 175, 'name' => "Poland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 176, 'name' => "Portugal", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 177, 'name' => "Puerto Rico", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 178, 'name' => "Qatar", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 179, 'name' => "Reunion", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 180, 'name' => "Romania", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 181, 'name' => "Russia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 182, 'name' => "Rwanda", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 183, 'name' => "Saint Helena", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 184, 'name' => "Saint Kitts And Nevis", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 185, 'name' => "Saint Lucia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 186, 'name' => "Saint Pierre and Miquelon", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 187, 'name' => "Saint Vincent And The Grenadines", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 188, 'name' => "Samoa", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 189, 'name' => "San Marino", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 190, 'name' => "Sao Tome and Principe", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 191, 'name' => "Saudi Arabia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 192, 'name' => "Senegal", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 193, 'name' => "Serbia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 194, 'name' => "Seychelles", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 195, 'name' => "Sierra Leone", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 196, 'name' => "Singapore", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 197, 'name' => "Slovakia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 198, 'name' => "Slovenia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 199, 'name' => "Smaller Territories of the UK", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 200, 'name' => "Solomon Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 201, 'name' => "Somalia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 202, 'name' => "South Africa", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 203, 'name' => "South Georgia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 204, 'name' => "South Sudan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 205, 'name' => "Spain", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 206, 'name' => "Sri Lanka", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 207, 'name' => "Sudan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 208, 'name' => "Suriname", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 209, 'name' => "Svalbard And Jan Mayen Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 210, 'name' => "Swaziland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 211, 'name' => "Sweden", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 212, 'name' => "Switzerland", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 213, 'name' => "Syria", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 214, 'name' => "Taiwan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 215, 'name' => "Tajikistan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 216, 'name' => "Tanzania", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 217, 'name' => "Thailand", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 218, 'name' => "Togo", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 219, 'name' => "Tokelau", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 220, 'name' => "Tonga", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 221, 'name' => "Trinidad And Tobago", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 222, 'name' => "Tunisia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 223, 'name' => "Turkey", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 224, 'name' => "Turkmenistan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 225, 'name' => "Turks And Caicos Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 226, 'name' => "Tuvalu", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 227, 'name' => "Uganda", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 228, 'name' => "Ukraine", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 229, 'name' => "United Arab Emirates", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 230, 'name' => "United Kingdom", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 231, 'name' => "United States", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 232, 'name' => "United States Minor Outlying Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),),
    		array('id' => 233, 'name' => "Uruguay", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 234, 'name' => "Uzbekistan", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 235, 'name' => "Vanuatu", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 236, 'name' => "Vatican City State (Holy See)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 237, 'name' => "Venezuela", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 238, 'name' => "Vietnam", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 239, 'name' => "Virgin Islands (British)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 240, 'name' => "Virgin Islands (US)", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),   ),
    		array('id' => 241, 'name' => "Wallis And Futuna Islands", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 242, 'name' => "Western Sahara", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 243, 'name' => "Yemen", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 244, 'name' => "Yugoslavia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"), ),
    		array('id' => 245, 'name' => "Zambia", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    		array('id' => 246, 'name' => "Zimbabwe", 'created_at' => date("Y-m-d H:i:s"), 'updated_at' => date("Y-m-d H:i:s"),  ),
    	);

    	DB::table('location_countries')->insert($countries);

    }
}
